# Generated by Django 3.2.3 on 2021-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpost', '0002_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.IntegerField(),
        ),
    ]
